spring:
  application:
    name: schedule-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOSTNAME}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: root
    password: ${MYSQL_ROOT_PASSWORD}
  config:
    import:
      - optional:env.yml
      - optional:jpa.yml